version: '3'
services:
  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: make run
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file: .env
  postgres:
    image: postgres:11
    env_file:
      - .env
    ports:
      - "5432:5432"
